SELECT * FROM CALENDAR;

DELETE FROM CALENDAR;
COMMIT;

DROP TABLE PDS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_PDS;

CREATE TABLE PDS(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	FILENAME VARCHAR2(50) NOT NULL,
    DEL NUMBER(8) NOT NULL,
	READCOUNT NUMBER(8) NOT NULL,
	DOWNCOUNT NUMBER(8) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO PDS VALUES(SEQ_PDS.NEXTVAL, 'MIN', 'TEST', 'KILL THIS SHIT', 'FILE.FILE', 0, 0, 0, SYSDATE);
COMMIT;

SELECT * FROM PDS;

CREATE SEQUENCE SEQ_PDS
START WITH 1 INCREMENT BY 1;


SELECT * FROM (SELECT *  FROM PDS ORDER BY SEQ DESC) WHERE ROWNUM >= 11;

DELETE FROM PDS WHERE ID='MIN';
COMMIT;

SELECT * FROM (SELECT A.* , ROWNUM RNUM FROM (SELECT * FROM pds ORDER by seq desc) A ) WHERE RNUM >= 20 AND RNUM <= 30;